Fix typings with esm
devrnt/react-use-wizard pull request #165
Opened 2023-07-25 09:03 UTC by stuikomma

Hi, thanks for the lib! I am currently using it in my third project and got some type errors. This error appears when `"moduleResolution"` is set to `"bundler"`  in tsconfig.json.

```
TS7016: Could not find a declaration file for module 'react-use-wizard'.
'/path/to/my/project/node_modules/react-use-wizard/dist/react-use-wizard.esm.js' implicitly has an 'any' type.

There are types at '/path/to/my/project/node_modules/react-use-wizard/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". 
The 'react-use-wizard' library may need to update its package.json or typings.
```

In my local test, this change fixed it.

2023-07-25 09:52 UTC, devrnt requested changes
Thanks for this PR, I really appreciate it

2023-07-25 10:12 UTC, stuikomma commented on package.json
> +      }
True, updated.

2023-07-25 14:04 UTC, stuikomma commented
@devrnt Would you mind overriding the failing job? Or fixing it? I am not familiar with you CI setup. Otherwise, I'll just wait for #167 which should also fix it.

2023-07-25 19:05 UTC, devrnt commented
Can you sync your branch? Pipeline issue should be resolved

2023-07-26 08:06 UTC, devrnt approved these changes

2023-07-26 08:17 UTC, merged

2023-07-26 08:22 UTC, devrnt commented
[v.2.2.3](https://github.com/devrnt/react-use-wizard/releases/tag/v2.2.3)